spring.application.name=pr

# Run backend on port 8080
server.port=8080

# Use H2 memory database
spring.datasource.url=jdbc:h2:mem:loginapp

# Driver for H2
spring.datasource.driverClassName=org.h2.Driver

# Default username
spring.datasource.username=sa

# No password
spring.datasource.password=

# Auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# Enable H2 browser console
spring.h2.console.enabled=true

# H2 console path
spring.h2.console.path=/h2-console


